apiVersion: v1
kind: ConfigMap
metadata:
  name: bnpl-config
  namespace: bnpl-platform
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  JWT_ISSUER: "https://api.yourcompany.com"
  JWT_AUDIENCE: "https://api.yourcompany.com"
  PLATFORM_NAME: "BNPL Platform"
  NORWEGIAN_TIMEZONE: "W. Europe Standard Time"
  NORWEGIAN_CURRENCY: "NOK"
  NORWEGIAN_LOCALE: "nb-NO"