apiVersion: v1
kind: Secret
metadata:
  name: bnpl-secrets
  namespace: bnpl-platform
type: Opaque
stringData:
  # JWT Secret Key (base64 encoded in production)
  JWT_KEY: "your-super-secret-jwt-key-change-in-production"
  
  # Database Connection Strings
  DB_PAYMENT: "Server=sql-server;Database=BNPL_Payment;User Id=sa;Password=YourPassword;TrustServerCertificate=true"
  DB_RISK: "Server=sql-server;Database=BNPL_Risk;User Id=sa;Password=YourPassword;TrustServerCertificate=true"
  DB_SETTLEMENT: "Server=sql-server;Database=BNPL_Settlement;User Id=sa;Password=YourPassword;TrustServerCertificate=true"
  DB_NOTIFICATION: "Server=sql-server;Database=BNPL_Notification;User Id=sa;Password=YourPassword;TrustServerCertificate=true"
  
  # Redis
  REDIS_CONNECTION: "redis:6379,password=YourRedisPassword"
  
  # External Services
  SENDGRID_API_KEY: "your-sendgrid-api-key"
  TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  
  # Norwegian Banking (if enabled)
  DNB_CLIENT_ID: "your-dnb-client-id"
  DNB_CLIENT_SECRET: "your-dnb-client-secret"